<p>
	<?php echo $this->form; ?>
	<hr>
	<?php echo $this->mensagem; ?>

	<?php
	if ($this->dado != ""){
		?>
		<table summary="" border="1">
			<caption>Listagem de Matéria(s)</caption>
			<tr>
				<th>Nome</th>
			</tr>
			<?php 
			if(isset($this->dado )){
				foreach ($this->dado as $materia ) {
						echo 	'<tr>' .
								'<td>' . $materia->nome . '</td>'.
								'</tr>';
				}
			}
			?>
		</table>
		<?php
	}
	?>
</p>
